### ISSUE TITLE
Running npm run setup

### ISSUE THREAD

**Issue by benjaminhayek** [kayyali18/node-backend-server#37]
Just so you know i got this error when i ran npm run setup, but was able to get the database going by creating the formula_1 database and running knex afterwards.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server-node@1.0.0 setup: `sudo -u postgres psql -c 'CREATE USER f1 WITH SUPERUSER CREATEDB --no-password'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server-node@1.0.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by kayyali18** [comment]
Thanks, I'll look into it ASAP

**Comment by kayyali18** [comment]
Issue Fixed, npm run setup is now obsolete. The instructions will reflect that. Thank you for the heads up!
